-
 name: Installing & Configuring AWS CLI
 hosts: machine2
 tasks:
  - name: installing AWS CLI
    shell: 
     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
     sudo apt -y install unzip
     unzip awscliv2.zip
     sudo ./aws/install  

  - name: Configuring Credentials
    shell: 
     aws --profile prueba2 configure set aws_access_key_id {{ ak }}
     aws --profile prueba2 configure set aws_secret_access_key {{ sak }}
