-
 name: Downloading AWS CLI 
 hosts: machine2
 tasks:
  - name: Step 1
    get_url:
     url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
     dest: awscliv2.zip
  
- 
  name: installing Unzip & Unzip AWS CLI
  hosts: machine2
  become: true
  tasks: 
    - name: install unzip
      apt:
        name: unzip
        state: present

    - name: unzipping AWS CLI
      shell: unzip -o awscliv2.zip

    - name: aws install
      shell: ./aws/install --update
- 
  name: Configuring AWS CLI
  hosts: machine2
  tasks: 
    - name: Giving AK
      shell: aws --profile prueba2 configure set aws_access_key_id {{ ak }}

    - name: Giving SAK
      shell: aws --profile prueba2 configure set aws_secret_access_key {{ sak }}

