-
 name: Downloading AWS CLI 
 hosts: machine2
 tasks:
  - name: Step 1
    uri:
     url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
     dest: awscliv2.zip
  
- 
  name: installing Unzip & Unzip AWS CLI
  hosts: machine2
  become: true
  tasks: 
    - name: install unzip
      apt:
        name: unzip
        state: present
    - name: unzipping AWS CLI
      shell: 
      unzip awscliv2.zip
      ./aws/install
- 
  name: Configuring AWS CLI
  hosts: machine2
  tasks: 
    - name: Configuring Credentials
      shell: 
      aws --profile prueba2 configure set aws_access_key_id {{ ak }}
      aws --profile prueba2 configure set aws_secret_access_key {{ sak }}

