-
 name: AWS Docker Login
 hosts: build
 tasks:
  - name: execute script on server
    shell: aws ecr get-login-password | docker login --username AWS --password-stdin {{ ecr_url }}

  - name: Tag image
    shell: docker tag {{ image_tag }} {{ ecr_url }}:{{ image_tag }}
    
  - name: Push Image
    shell: docker push {{ ecr_url }}:{{ image_tag }}