-
 name: Initializing Node Exporter
 hosts: deploy
 tasks:
  - name: creating folder
    shell: mkdir /home/ubuntu/node-exporter
  - name: directory copy to remote device
    copy:
        src: "{{ workspace ~ '/ansible/node-compose.yml' }}"
        dest: /home/ubuntu/node-exporter/node-compose.yml
        owner: ubuntu
        group: ubuntu
  - name: run node-compose
    shell: docker compose -f /home/ubuntu/node-exporter/node-compose.yml up -d