-
 name: play 1
 hosts: machine1,machine2
 tasks:
  - name: execute script on server
    script: config-machine-1.sh

-name: directory copy to remote device
 hosts: machine1
 copy:
    src: /home/ubuntu/jenkins/workspace/demo pipeline/app/
    dest: /app
    owner: ubuntu
    group: ubuntu