-
 name: copying files
 hosts: machine1
 tasks:
  - name: directory copy to remote device
    copy:
      src: /home/ubuntu/jenkins/workspace/demo pipeline/app/
      dest: /home/ubuntu/app
      owner: ubuntu
      group: ubuntu