# -
#  name: play 1
#  hosts: machine1,machine2
#  tasks:
#   - name: execute script on server
#     script: config-machine-1.sh

-
 name: copying files
 hosts: machine1
 tasks:
  - name: directory copy to remote device
    copy:
      src: /home/ubuntu/jenkins/workspace/demo pipeline/app/
      dest: /home/ubuntu/app
      owner: ubuntu
      group: ubuntu