-
 name: copying files
 hosts: build
 tasks:
  - name: directory copy to remote device
    copy:
      src: {{ workspace ~ "/app/" }}
      dest: /home/ubuntu/app
      owner: ubuntu
      group: ubuntu